- version1.txt
> Starting version 1 text

- version1.txt
> Version 1 text finished

- version2.txt
> Wrote version 2 text-file

- main.css
- utbildningar.css
- utbildningar.html
> Utbildningar.html

- main.css
- utbildningar.css
- utbildningar.html
> Utbildningar.css

- rules.txt
> Started writing rules for coding

- JS/countryElement.js
> JS-code from meeting with Erik

- header.css
- header.js
> created header

- header.js
> updated header

- index.html
> First page fixes

- CSS/header.css
- HTML/destinationer.html
- HTML/index.html
- HTML/utbildningar.html
- JS/header.js
> Header linked to HTML

- Databases/continents.js
Contains each continent with name and their corresponding countries with ID. #43
> Created database-file for Continents

- CSS/destinationer.css
- CSS/footer.css
- HTML/destinationer.html
- HTML/index.html
- HTML/utbildningar.html
- JS/footer.js
And some CSS fix to make it work. Fixes #42
> Linked footer to all HTML

- JS/buildCountry.js
> Updated buildCountry

- CSS/popup.css
- JS/popup.js
> pop up div

- JS/averageGrade.js
Can calculate the average grade of ALL comments in a database. Need to find out how to make it so that it only calculates the score for the selected programme/country. (Using ID?) #59
> Created first averageGrade-function

- CSS/destinationer.css
- JS/buildCountry.js
- destinationer.html
> More updates on buildCountry

- JS/header.js
> beginning of hamburger meny

- CSS/header.css
- CSS/utbildningar.css
- JS/header.js
> updated css for burgermenu

- Databases/database.js
- JS/buildCity.js
- JS/buildCountry.js
- destinationer.html
> Updates on buildCity

- JS/buildCity.js
- JS/buildCountry.js
- JS/destinationer.js
- destinationer.html
> More updates on countries

- JS/buildProgram.js
- utbildningar.html
> Buildprogram

- CSS/destinationer.css
- JS/buildCountry.js
- destinationer.html
> Select styling and more

- JS/averageGrade.js
- JS/buildProgram.js
- JS/test.html
- utbildningar.html
> Average grade finished

- CSS/destinationer.css
> Some more updates on styling

- CSS/utbildningar.css
- utbildningar.html
> fixed image

- JS/buildCountry.js
- JS/destinationer.js
- destinationer.html
> Converting to inner.HTML

- JS/buildProgram.js
- utbildningar.html
> filter country

- JS/buildCountry.js
- JS/chooseCity.js
- JS/chooseCountry.js
> Empty selector onload

- JS/buildCity.js
- JS/buildCountry.js
- destinationer.html
> Added some comments and small updates

- JS/buildProgram.js
> filter on countries and subjects

- CSS/destinationer.css
- JS/buildCity.js
> Added averageGrade function to each city

- CSS/utbildningar.css
- JS/buildProgram.js
Need to add show more functionality
> Added more information to the programdivs (NEW)

- CSS/utbildningar.css
- JS/buildProgram.js
- JS/showMoreLessProgrammes.js
- utbildningar.html
Works for standard loaded, doesn't work when filtered #114
> Function to show more or less

- JS/buildCity.js
- JS/chooseCity.js
> Small changes

- JS/buildCity.js
> Solving the problem with NaN on rating

- JS/buildContinents.js
- JS/buildProgram.js
> fixed popup countries

- JS/buildCity.js
- JS/buildCountry.js
- JS/header.js
> fixed comments and hamburger

- JS/buildContinents.js
> done with pop up countries

- Databases/continents.js
- JS/buildContinents.js
> fixed with continent opacity

- CSS/homepage.css
- CSS/main.css
- CSS/popup.css
- JS/buildContinents.js
> Continent session storage

- JS/buildContinents.js
- JS/header.js
> Started trying to fix hambureger menu problem

- CSS/destinationer.css
- JS/buildCountry.js
> Problem with utbildning-button solved

- Databases/continents.js
- Databases/database.js
Changed from South America to North America
> Fixed Mexicos ContinentId

- CSS/popup.css
- JS/buildContinents.js
- JS/buildCountry.js
And some formatting and comments
> Disclaimer when no countries
